server:
  port: 20002
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
#  application:
#    name: coupon-calculation-serv
  cloud:
    nacos:
      discovery:
        #Nacos 服务器地址,可以配置多个, 用,分割
        server-addr: localhost:8847
        #注册到 Nacos 上的服务名称
        servive: coupon-calculation-serv
        #各个微服务向Nacos发送心跳的时间间,单位是毫秒
        heart-beat-interval: 5000
        #心跳检测的超时时间，一定要大于heart-beat-interval
        heart-beat-timeout: 20000
        #元数据-可以自己随便定制
        meatedate:
          myData: xyz
        #命名空间 ID，进行数据隔离
        namespace: dev
        #两个服务如果要调用，一定要在同一个group
        group: myGroup
        #以下非必须
        register-enabled: true
        #优先从本地缓存读取服务配置
        naming-load-cache-at-start: false
logging:
  level:
    top.mqxu.coupon: debug

# 开启所有management端点
management:
  endpoints:
    web:
      exposure:
        include: "*"