server:
  port: 20000
spring:
  cloud:
    nacos:
      discovery:
        #Nacos 服务器地址,可以配置多个, 用,分割
        server-addr: localhost:8847
        #注册到 Nacos 上的服务名称
        servive: coupon-template-serv
        #各个微服务向Nacos发送心跳的时间间,单位是毫秒
        heart-beat-interval: 5000
        #心跳检测的超时时间，一定要大于heart-beat-interval
        heart-beat-timeout: 20000
        #元数据-可以自己随便定制
        meatedate:
          myData: abc
        #命名空间 ID，进行数据隔离
        namespace: dev
        #两个服务如果要调用，一定要在同一个group
        group: myGroup
        #以下非必须
        register-enabled: true
        #优先从本地缓存读取服务配置
        naming-load-cache-at-start: false
#  application:
#    # 定义应用名称
#    name: coupon-template-serv
#  datasource:
#    # mysql数据源
#    url: jdbc:mysql://127.0.0.1:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    username: root
#    password: 12345678
#    # 指定数据源 DataSource 类型
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 数据库连接池参数配置，比如大小、超时时间、是否自动提交等
#    hikari:
#      pool-name: CloudCouponHikari
#      connection-timeout: 5000
#      idle-timeout: 30000
#      maximum-pool-size: 10
#      minimum-idle: 5
#      max-lifetime: 60000
#      auto-commit: true
#  jpa:
#    show-sql: true
#    hibernate:
#      # 在生产环境全部为 none，防止 ddl 结构被自动执行，破坏生产数据
#      ddl-auto: none
#    # 在日志中打印经过格式化的SQL语句
#    properties:
#      hibernate.format_sql: true
#      hibernate.show_sql: true
#    open-in-view: false